## -*- docker-image-name: "spotify/bigtable-emulator" -*-

FROM golang:1.6
MAINTAINER Robert Gruener "robertg@spotify.com"

# Install netcat
RUN apt-get update
RUN apt-get install -y netcat

# Get bigtable go package
RUN go get google.golang.org/cloud/bigtable

ADD bigtable-server.go /go/bin/bigtable-server.go
RUN go build /go/bin/bigtable-server.go
ENTRYPOINT ["/go/bigtable-server"]
EXPOSE 8080
